#!/bin/bash

docker run \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/shadow:/etc/shadow:ro \
    -v /etc/group:/etc/group:ro \
    -v /usr/lib/locale:/usr/lib/locale:ro \
    -v ${HOME}/.bash_history:${HOME}/.bash_history \
    -v ${ZEPHYR_BASE}:${ZEPHYR_BASE} \
    -v /dev:/dev \
    -e LANG=C.UTF-8 \
    -e LC_ALL=C.UTF-8 \
    -e TZ=$(cat /etc/timezone) \
    --privileged \
    --group-add=plugdev \
    -w ${PWD} \
    -v ${PWD}:${PWD} \
    -u $(id -u):$(id -g) \
    --rm \
    -it \
    inakimalerba/malva-environment bash
